// <auto-generated />
namespace Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InternshipRedesign : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InternshipRedesign));
        
        string IMigrationMetadata.Id
        {
            get { return "201609031410126_InternshipRedesign"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
