namespace Service.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class EntityFixes : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Internships", "ApplicationUserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Theses", "ApplicationUserId", "dbo.AspNetUsers");
            DropIndex("dbo.Activities", new[] { "CodeName" });
            DropIndex("dbo.Companies", new[] { "CompanyName" });
            DropIndex("dbo.Companies", new[] { "CodeName" });
            DropIndex("dbo.CompanyCategories", new[] { "CodeName" });
            DropIndex("dbo.CompanySizes", new[] { "CodeName" });
            DropIndex("dbo.Countries", new[] { "CodeName" });
            DropIndex("dbo.Internships", new[] { "ApplicationUserId" });
            DropIndex("dbo.InternshipAmountTypes", new[] { "CodeName" });
            DropIndex("dbo.Currencies", new[] { "CodeName" });
            DropIndex("dbo.HomeOfficeOptions", new[] { "CodeName" });
            DropIndex("dbo.InternshipCategories", new[] { "CodeName" });
            DropIndex("dbo.Theses", new[] { "ApplicationUserId" });
            DropIndex("dbo.ThesisTypes", new[] { "CodeName" });
            DropIndex("dbo.InternshipDurationTypes", new[] { "CodeName" });
            DropIndex("dbo.StudentStatusOptions", new[] { "CodeName" });
            DropIndex("dbo.Messages", new[] { "CodeName" });
            DropIndex("dbo.Emails", new[] { "CodeName" });
            DropIndex("dbo.Languages", new[] { "CodeName" });
            DropIndex("dbo.Logs", new[] { "CodeName" });
            AddColumn("dbo.Messages", "Created", c => c.DateTime(nullable: false));
            AddColumn("dbo.Messages", "Updated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Activities", "CodeName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Companies", "CompanyName", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Companies", "CodeName", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.CompanyCategories", "CodeName", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.CompanyCategories", "Name", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.CompanySizes", "CompanySizeName", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.CompanySizes", "CodeName", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Countries", "CountryCode", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Countries", "CountryName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Countries", "CodeName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Internships", "ApplicationUserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.InternshipAmountTypes", "AmountTypeName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.InternshipAmountTypes", "CodeName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Currencies", "CurrencyName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Currencies", "CodeName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.HomeOfficeOptions", "HomeOfficeName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.HomeOfficeOptions", "CodeName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.InternshipCategories", "CodeName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.InternshipCategories", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Theses", "ApplicationUserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.ThesisTypes", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.ThesisTypes", "CodeName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.InternshipDurationTypes", "DurationName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.InternshipDurationTypes", "CodeName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.StudentStatusOptions", "StatusName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.StudentStatusOptions", "CodeName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Messages", "CodeName", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Emails", "CodeName", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Languages", "CodeName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Languages", "LanguageName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Logs", "CodeName", c => c.String(nullable: false, maxLength: 100));
            CreateIndex("dbo.Activities", "CodeName");
            CreateIndex("dbo.Companies", "CompanyName");
            CreateIndex("dbo.Companies", "CodeName");
            CreateIndex("dbo.CompanyCategories", "CodeName");
            CreateIndex("dbo.CompanySizes", "CodeName");
            CreateIndex("dbo.Countries", "CodeName");
            CreateIndex("dbo.Internships", "ApplicationUserId");
            CreateIndex("dbo.InternshipAmountTypes", "CodeName");
            CreateIndex("dbo.Currencies", "CodeName");
            CreateIndex("dbo.HomeOfficeOptions", "CodeName");
            CreateIndex("dbo.InternshipCategories", "CodeName");
            CreateIndex("dbo.Theses", "ApplicationUserId");
            CreateIndex("dbo.ThesisTypes", "CodeName");
            CreateIndex("dbo.InternshipDurationTypes", "CodeName");
            CreateIndex("dbo.StudentStatusOptions", "CodeName");
            CreateIndex("dbo.Messages", "CodeName");
            CreateIndex("dbo.Emails", "CodeName");
            CreateIndex("dbo.Languages", "CodeName");
            CreateIndex("dbo.Logs", "CodeName");
            AddForeignKey("dbo.Internships", "ApplicationUserId", "dbo.AspNetUsers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Theses", "ApplicationUserId", "dbo.AspNetUsers", "Id", cascadeDelete: true);
            DropColumn("dbo.Messages", "MessageCreated");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Messages", "MessageCreated", c => c.DateTime(nullable: false));
            DropForeignKey("dbo.Theses", "ApplicationUserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Internships", "ApplicationUserId", "dbo.AspNetUsers");
            DropIndex("dbo.Logs", new[] { "CodeName" });
            DropIndex("dbo.Languages", new[] { "CodeName" });
            DropIndex("dbo.Emails", new[] { "CodeName" });
            DropIndex("dbo.Messages", new[] { "CodeName" });
            DropIndex("dbo.StudentStatusOptions", new[] { "CodeName" });
            DropIndex("dbo.InternshipDurationTypes", new[] { "CodeName" });
            DropIndex("dbo.ThesisTypes", new[] { "CodeName" });
            DropIndex("dbo.Theses", new[] { "ApplicationUserId" });
            DropIndex("dbo.InternshipCategories", new[] { "CodeName" });
            DropIndex("dbo.HomeOfficeOptions", new[] { "CodeName" });
            DropIndex("dbo.Currencies", new[] { "CodeName" });
            DropIndex("dbo.InternshipAmountTypes", new[] { "CodeName" });
            DropIndex("dbo.Internships", new[] { "ApplicationUserId" });
            DropIndex("dbo.Countries", new[] { "CodeName" });
            DropIndex("dbo.CompanySizes", new[] { "CodeName" });
            DropIndex("dbo.CompanyCategories", new[] { "CodeName" });
            DropIndex("dbo.Companies", new[] { "CodeName" });
            DropIndex("dbo.Companies", new[] { "CompanyName" });
            DropIndex("dbo.Activities", new[] { "CodeName" });
            AlterColumn("dbo.Logs", "CodeName", c => c.String(maxLength: 100));
            AlterColumn("dbo.Languages", "LanguageName", c => c.String(maxLength: 50));
            AlterColumn("dbo.Languages", "CodeName", c => c.String(maxLength: 50));
            AlterColumn("dbo.Emails", "CodeName", c => c.String(maxLength: 100));
            AlterColumn("dbo.Messages", "CodeName", c => c.String(maxLength: 100));
            AlterColumn("dbo.StudentStatusOptions", "CodeName", c => c.String(maxLength: 50));
            AlterColumn("dbo.StudentStatusOptions", "StatusName", c => c.String(maxLength: 50));
            AlterColumn("dbo.InternshipDurationTypes", "CodeName", c => c.String(maxLength: 50));
            AlterColumn("dbo.InternshipDurationTypes", "DurationName", c => c.String(maxLength: 50));
            AlterColumn("dbo.ThesisTypes", "CodeName", c => c.String(maxLength: 50));
            AlterColumn("dbo.ThesisTypes", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.Theses", "ApplicationUserId", c => c.String(maxLength: 128));
            AlterColumn("dbo.InternshipCategories", "Name", c => c.String(maxLength: 50));
            AlterColumn("dbo.InternshipCategories", "CodeName", c => c.String(maxLength: 50));
            AlterColumn("dbo.HomeOfficeOptions", "CodeName", c => c.String(maxLength: 50));
            AlterColumn("dbo.HomeOfficeOptions", "HomeOfficeName", c => c.String(maxLength: 50));
            AlterColumn("dbo.Currencies", "CodeName", c => c.String(maxLength: 50));
            AlterColumn("dbo.Currencies", "CurrencyName", c => c.String(maxLength: 50));
            AlterColumn("dbo.InternshipAmountTypes", "CodeName", c => c.String(maxLength: 50));
            AlterColumn("dbo.InternshipAmountTypes", "AmountTypeName", c => c.String(maxLength: 50));
            AlterColumn("dbo.Internships", "ApplicationUserId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Countries", "CodeName", c => c.String(maxLength: 50));
            AlterColumn("dbo.Countries", "CountryName", c => c.String(maxLength: 50));
            AlterColumn("dbo.Countries", "CountryCode", c => c.String(maxLength: 50));
            AlterColumn("dbo.CompanySizes", "CodeName", c => c.String(maxLength: 100));
            AlterColumn("dbo.CompanySizes", "CompanySizeName", c => c.String(maxLength: 100));
            AlterColumn("dbo.CompanyCategories", "Name", c => c.String(maxLength: 100));
            AlterColumn("dbo.CompanyCategories", "CodeName", c => c.String(maxLength: 100));
            AlterColumn("dbo.Companies", "CodeName", c => c.String(maxLength: 100));
            AlterColumn("dbo.Companies", "CompanyName", c => c.String(maxLength: 100));
            AlterColumn("dbo.Activities", "CodeName", c => c.String(maxLength: 50));
            DropColumn("dbo.Messages", "Updated");
            DropColumn("dbo.Messages", "Created");
            CreateIndex("dbo.Logs", "CodeName");
            CreateIndex("dbo.Languages", "CodeName");
            CreateIndex("dbo.Emails", "CodeName");
            CreateIndex("dbo.Messages", "CodeName");
            CreateIndex("dbo.StudentStatusOptions", "CodeName");
            CreateIndex("dbo.InternshipDurationTypes", "CodeName");
            CreateIndex("dbo.ThesisTypes", "CodeName");
            CreateIndex("dbo.Theses", "ApplicationUserId");
            CreateIndex("dbo.InternshipCategories", "CodeName");
            CreateIndex("dbo.HomeOfficeOptions", "CodeName");
            CreateIndex("dbo.Currencies", "CodeName");
            CreateIndex("dbo.InternshipAmountTypes", "CodeName");
            CreateIndex("dbo.Internships", "ApplicationUserId");
            CreateIndex("dbo.Countries", "CodeName");
            CreateIndex("dbo.CompanySizes", "CodeName");
            CreateIndex("dbo.CompanyCategories", "CodeName");
            CreateIndex("dbo.Companies", "CodeName");
            CreateIndex("dbo.Companies", "CompanyName");
            CreateIndex("dbo.Activities", "CodeName");
            AddForeignKey("dbo.Theses", "ApplicationUserId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Internships", "ApplicationUserId", "dbo.AspNetUsers", "Id");
        }
    }
}
