using System;
using System.Collections.Generic;
using System.Linq;
using Service.Context;
using System.Threading.Tasks;
using System.Web.Mvc;
using Service.Services.Questionnaires;
using UI.Base;
using UI.Builders.Form;
using UI.Builders.Form.Forms;
using UI.Builders.Master;
using UI.Events;
using UI.Exceptions;

namespace Web.Controllers
{
    [Authorize]
    public class FormController : BaseController
    {
        readonly FormBuilder _formBuilder;

        public FormController(IAppContext appContext, IServiceEvents serviceEvents, MasterBuilder masterBuilder, FormBuilder formBuilder) : base(appContext, serviceEvents, masterBuilder)
        {
            _formBuilder = formBuilder;
        }

        #region Actions

        [Route("Zajem/Staz/{id}/{codeName}")]
        public async Task<ActionResult> Internship(int? id, string codeName)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var model = await _formBuilder.BuildInternshipViewAsync((int) id);

            if (model == null)
            {
                return HttpNotFound();
            }

            return View(model);
        }

        [Route("Zajem/ZaverecnaPrace/{id}/{codeName}")]
        public async Task<ActionResult> Thesis(int? id, string codeName)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var model = await _formBuilder.BuildThesisViewAsync((int) id);

            if (model == null)
            {
                return HttpNotFound();
            }

            return View(model);
        }

        #endregion

        #region POST actions

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Zajem/Staz/{id}/{codeName}")]
        public async Task<ActionResult> Internship(FormInternshipForm form)
        {
            // validate form
            if (!ModelStateWrapper.IsValid)
            {
                var model = await _formBuilder.BuildInternshipViewAsync(form.InternshipID, form);

                return View(model);
            }

            try
            {
                // get questionnaire data
                GetQuestionnaireQuestionsFromRequest(form.FieldGuids);

                await _formBuilder.SaveInternshipForm(form);

                var model = await _formBuilder.BuildInternshipViewAsync(form.InternshipID);

                // set form status
                model.InternshipForm.FormResult.IsSuccess = true;

                return View(model);
            }
            catch (UiException ex)
            {
                ModelStateWrapper.AddError(ex.Message);

                var model = await _formBuilder.BuildInternshipViewAsync(form.InternshipID, form);

                return View(model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Zajem/ZaverecnaPrace/{id}/{codeName}")]
        public async Task<ActionResult> Thesis(FormThesisForm form)
        {
            // validate form
            if (!ModelStateWrapper.IsValid)
            {
                var model = await _formBuilder.BuildThesisViewAsync(form.ThesisID, form);

                return View(model);
            }

            try
            {
                await _formBuilder.SaveThesisForm(form);

                var model = await _formBuilder.BuildThesisViewAsync(form.ThesisID);

                // set form status
                model.ThesisForm.FormResult.IsSuccess = true;

                return View(model);
            }
            catch (UiException ex)
            {
                ModelStateWrapper.AddError(ex.Message);

                var model = await _formBuilder.BuildThesisViewAsync(form.ThesisID, form);

                return View(model);
            }
        }

        #endregion

        #region Helper methods

        private IList<IQuestion> GetQuestionnaireQuestionsFromRequest(IList<string> fieldGuids)
        {
            // use specific form field names generated by JS
            var questionDataPrefix = "Data_";
            var fieldDataSeparator = '_';

            var questions = new List<IQuestion>();

            if (fieldGuids == null)
            {
                return new List<IQuestion>();
            }

            foreach (var questionGuid in fieldGuids)
            {
                // get question specific data from submitted form data
                var dataPrefix = questionDataPrefix + questionGuid;

                var questionData = new List<IQuestionData>();

                // get questions data
                foreach (var key in Request.Form.AllKeys.Where(m => m.StartsWith(dataPrefix, StringComparison.OrdinalIgnoreCase)))
                {
                    if (string.IsNullOrEmpty(key))
                    {
                        continue;
                    }

                    var keyValues = key.Split(fieldDataSeparator);

                    if (keyValues.Length != 3)
                    {
                        // invalid number of params
                        continue;
                    }

                    var dataName = keyValues[2];
                    var value = Request.Form[key];
                }

                // add question
                questions.Add(new Question()
                {
                    Data = questionData,
                });
            }

            return questions;
        }

        #endregion
    }
}